# Generated by Django 4.2.7 on 2023-11-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(max_length=255)),
                ('booked_by_email', models.EmailField(max_length=254)),
                ('booked_by_phone', models.CharField(max_length=20)),
                ('cc', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('meeting_id', models.CharField(max_length=255)),
                ('meeting_link', models.TextField(null=True)),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
