# Generated by Django 4.2.7 on 2023-11-20 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_credentials_updated_at', models.DateTimeField(null=True)),
                ('google_access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('google_scope', models.TextField()),
                ('google_token_type', models.CharField(blank=True, max_length=50, null=True)),
                ('google_token_expires_in', models.IntegerField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
