# Generated by Django 4.2.7 on 2023-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='google_token_expires_in',
            field=models.IntegerField(),
        ),
    ]
