# Generated by Django 4.2.7 on 2023-11-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_google_token_expires_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='google_credentials_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='google_scope',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='google_token_expires_in',
            field=models.IntegerField(blank=True),
        ),
    ]
