# Generated by Django 4.2.7 on 2023-11-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_google_credentials_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='google_token_expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
