# Generated by Django 4.2.7 on 2023-12-19 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_account_google_token_expires_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='google_access_token',
        ),
        migrations.RemoveField(
            model_name='account',
            name='google_credentials_updated_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='google_scope',
        ),
        migrations.RemoveField(
            model_name='account',
            name='google_token_expires_in',
        ),
        migrations.RemoveField(
            model_name='account',
            name='google_token_type',
        ),
        migrations.AddField(
            model_name='account',
            name='google_account',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
