# Generated by Django 4.2.7 on 2023-12-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarProvider',
        ),
        migrations.RemoveField(
            model_name='emailprovider',
            name='user',
        ),
        migrations.DeleteModel(
            name='GoogleAccount',
        ),
        migrations.DeleteModel(
            name='EmailProvider',
        ),
    ]
