# Generated by Django 4.2.7 on 2023-12-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_calendarprovider_remove_emailprovider_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mail_signature',
            field=models.TextField(blank=True),
        ),
    ]
