# Generated by Django 4.2.7 on 2024-02-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_mail_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('max_emails_per_day', models.PositiveIntegerField()),
                ('max_emails_per_month', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('features', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='last_billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.plan'),
        ),
    ]
