# Generated by Django 4.2.7 on 2024-02-18 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_emails_at_once',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='google_account',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.plan'),
        ),
    ]
