# Generated by Django 4.2.7 on 2024-02-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_plan_max_emails_at_once_alter_account_google_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mail_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='google_account',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
