# Generated by Django 4.2.7 on 2024-03-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_mail_settings_alter_account_google_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
