# Generated by Django 4.2.7 on 2024-03-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_verificationcode_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mail_settings',
            field=models.JSONField(default={}),
        ),
    ]
