# Generated by Django 4.2.7 on 2024-03-13 18:00

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_email_provider_alter_account_mail_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(default=accounts.models.Plan.get_default_plan, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.plan'),
        ),
    ]
