# Generated by Django 4.2.7 on 2024-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_account_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_emails_at_once',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
