// User
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

// root 
export const SET_TOKEN_VERIFIED = "SET_TOKEN_VERIFIED " 


// UI
export const SHOW_TOAST = "SHOW_TOAST";
export const CLEAR_TOAST = "CLEAR_TOAST";


// contacts

export const ADD_CONTACT ="ADD CONTACT";
export const UPDATE_CONTACT="UPDATE_CONTACT";
export const ADD_CONTACTS_MANY="ADD_CONTACT_MANY";
export const SET_CONTACTS = "SET_CONTACTS"
export const DELETE_CONTACT = "DELETE_CONTACT";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_CATEGORY= "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
