# Generated by Django 4.2.7 on 2023-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0002_alter_mail_options_mail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
    ]
