# Generated by Django 4.2.7 on 2023-11-18 11:07

from django.db import migrations, models
import django.db.models.deletion
import mail_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0003_mail_failed_mail_failure_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(upload_to=mail_service.models.attachment_upload_path)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_service.mail')),
            ],
        ),
    ]
