# Generated by Django 4.2.7 on 2023-11-18 18:20

import django.core.validators
from django.db import migrations, models
import mail_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0004_mailattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='attachment_file',
            field=models.FileField(upload_to=mail_service.models.attachment_upload_path, validators=[django.core.validators.MaxValueValidator(limit_value=20971520)]),
        ),
    ]
