# Generated by Django 4.2.7 on 2023-12-03 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_service', '0005_mailtemplate_alter_mailattachment_attachment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailtemplate',
            old_name='template',
            new_name='body',
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='name',
            field=models.CharField(default='Template Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='parameters',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(default='', max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
