# Generated by Django 4.2.7 on 2023-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0007_mail_user_alter_mailtemplate_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
