# Generated by Django 4.2.7 on 2023-12-20 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_service', '0008_mail_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='to',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
