# Generated by Django 4.2.7 on 2023-12-22 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_service', '0009_alter_mail_bcc_alter_mail_cc_alter_mail_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='mailattachment',
            name='mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_service.mail'),
        ),
        migrations.AddConstraint(
            model_name='mailattachment',
            constraint=models.CheckConstraint(check=models.Q(('mail__isnull', False)), name='either_mail_or_bulk_email_is_required'),
        ),
        migrations.AddField(
            model_name='bulkmail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mail',
            name='bulk_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to='mail_service.bulkmail'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='bulk_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_service.bulkmail'),
        ),
    ]
