# Generated by Django 4.2.7 on 2023-12-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0010_bulkmail_alter_mailattachment_mail_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mailattachment',
            name='either_mail_or_bulk_email_is_required',
        ),
        migrations.AddConstraint(
            model_name='mailattachment',
            constraint=models.CheckConstraint(check=models.Q(('bulk_mail__isnull', False), ('mail__isnull', False), _connector='OR'), name='either_mail_or_bulk_email_is_required'),
        ),
    ]
