# Generated by Django 4.2.7 on 2023-12-23 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0011_remove_mailattachment_either_mail_or_bulk_email_is_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkmail',
            name='template',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
