# Generated by Django 4.2.7 on 2023-12-23 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0012_bulkmail_created_at_bulkmail_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='cc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='to',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
