# Generated by Django 4.2.7 on 2024-03-13 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_service', '0013_mailtemplate_cc_mailtemplate_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emails_sent', models.IntegerField(default=0)),
                ('contacts_created', models.IntegerField(default=0)),
                ('is_limit_warning_email_sent', models.BooleanField(default=False)),
                ('is_limit_reached_email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
