# Generated by Django 4.2.7 on 2026-03-29 10:51

from django.db import migrations, models
import mail_service.models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0014_emailusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailattachment",
            name="attachment_file",
            field=models.FileField(
                upload_to=mail_service.models.attachment_upload_path
            ),
        ),
    ]
