# Generated by Django 4.2.7 on 2026-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_product_remove_invoice_amount_remove_proforma_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("dispatched", "Dispatched"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="status",
            field=models.CharField(
                choices=[("issued", "Issued"), ("cancelled", "Cancelled")],
                default="issued",
                max_length=20,
            ),
        ),
    ]
