# Generated by Django 4.2.7 on 2026-03-31 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0003_deliverynote_status_invoice_status_proforma_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("TRY", "Turkish Lira"),
                    ("KES", "Kenyan Shilling"),
                    ("UGX", "Ugandan Shilling"),
                    ("TZS", "Tanzanian Shilling"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="pdf_needs_regeneration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="selected_template",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "delivery_note", "is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_note_instances",
                to="sales.template",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="generated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="document",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_documents",
                to="sales.template",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("TRY", "Turkish Lira"),
                    ("KES", "Kenyan Shilling"),
                    ("UGX", "Ugandan Shilling"),
                    ("TZS", "Tanzanian Shilling"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_needs_regeneration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="selected_template",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "invoice", "is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_instances",
                to="sales.template",
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("TRY", "Turkish Lira"),
                    ("KES", "Kenyan Shilling"),
                    ("UGX", "Ugandan Shilling"),
                    ("TZS", "Tanzanian Shilling"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proforma",
            name="pdf_needs_regeneration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proforma",
            name="selected_template",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "proforma", "is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proforma_instances",
                to="sales.template",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("TRY", "Turkish Lira"),
                    ("KES", "Kenyan Shilling"),
                    ("UGX", "Ugandan Shilling"),
                    ("TZS", "Tanzanian Shilling"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="pdf_needs_regeneration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quotation",
            name="selected_template",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "quotation", "is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_instances",
                to="sales.template",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("TRY", "Turkish Lira"),
                    ("KES", "Kenyan Shilling"),
                    ("UGX", "Ugandan Shilling"),
                    ("TZS", "Tanzanian Shilling"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="pdf_needs_regeneration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receipt",
            name="selected_template",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "receipt", "is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipt_instances",
                to="sales.template",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("quotation", "Quotation"),
                    ("proforma", "Proforma"),
                    ("delivery_note", "Delivery Note"),
                    ("receipt", "Receipt"),
                ],
                default="invoice",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="template",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="template",
            name="mapping",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="template",
            name="supported_currencies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional list of supported currency codes for this template.",
            ),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255, null=True)),
                ("tax_number", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                (
                    "supported_currencies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed currency codes, e.g. ['USD', 'EUR']",
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("TRY", "Turkish Lira"),
                            ("KES", "Kenyan Shilling"),
                            ("UGX", "Ugandan Shilling"),
                            ("TZS", "Tanzanian Shilling"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                ("invoice_prefix", models.CharField(default="INV", max_length=20)),
                ("quotation_prefix", models.CharField(default="QUO", max_length=20)),
                ("proforma_prefix", models.CharField(default="PRO", max_length=20)),
                ("receipt_prefix", models.CharField(default="REC", max_length=20)),
                ("delivery_note_prefix", models.CharField(default="DN", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="sales.company",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="sales.company",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="sales.company",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="sales.company",
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="sales.company",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="sales.company",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="sales.company",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="sales.company",
            ),
        ),
    ]
