# Generated by Django 4.2.7 on 2026-04-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_companymembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="storage_used_bytes",
            field=models.BigIntegerField(default=0),
        ),
    ]
