# Generated by Django 4.2.7 on 2026-04-08 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0007_documentevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSendingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("company", "Company"), ("user", "User")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("from_name", models.CharField(blank=True, max_length=255, null=True)),
                ("from_email", models.EmailField(max_length=254)),
                ("smtp_host", models.CharField(max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_username", models.CharField(max_length=255)),
                ("smtp_password_encrypted", models.TextField()),
                (
                    "security_type",
                    models.CharField(
                        choices=[("tls", "TLS"), ("ssl", "SSL"), ("none", "None")],
                        default="tls",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_test_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_test_error", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_sending_configs",
                        to="sales.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_sending_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["owner_type", "name"],
            },
        ),
    ]
