# Generated by Django 4.2.7 on 2026-04-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_emailsendingconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="tax_label",
            field=models.CharField(default="VAT", max_length=50),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="tax_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "Tax added on top"),
                    ("inclusive", "Tax included in prices"),
                ],
                default="exclusive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="tax_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_label",
            field=models.CharField(default="VAT", max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "Tax added on top"),
                    ("inclusive", "Tax included in prices"),
                ],
                default="exclusive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proforma",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proforma",
            name="tax_label",
            field=models.CharField(default="VAT", max_length=50),
        ),
        migrations.AddField(
            model_name="proforma",
            name="tax_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "Tax added on top"),
                    ("inclusive", "Tax included in prices"),
                ],
                default="exclusive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="proforma",
            name="tax_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="proforma",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax_label",
            field=models.CharField(default="VAT", max_length=50),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "Tax added on top"),
                    ("inclusive", "Tax included in prices"),
                ],
                default="exclusive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="quotation",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="tax_label",
            field=models.CharField(default="VAT", max_length=50),
        ),
        migrations.AddField(
            model_name="receipt",
            name="tax_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "Tax added on top"),
                    ("inclusive", "Tax included in prices"),
                ],
                default="exclusive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="receipt",
            name="tax_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="receipt",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
