# Generated by Django 4.2.7 on 2026-04-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_deliverynote_issue_date_deliverynote_tax_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="sales.customer",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="sales.quotation",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="proforma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="sales.proforma",
            ),
        ),
    ]
