# Generated by Django 4.2.7 on 2026-04-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_invoice_customer_invoice_quotation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("company", "invoice_number")},
        ),
    ]
