# Generated by Django 4.2.7 on 2026-04-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0015_backfill_company_number_counters"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentevent",
            new_name="sales_docum_company_e03fd5_idx",
            old_name="sales_docum_company_bbdced_idx",
        ),
        migrations.RenameIndex(
            model_name="documentevent",
            new_name="sales_docum_source__3ea424_idx",
            old_name="sales_docum_source__487e1b_idx",
        ),
    ]
