# Generated by Django 4.2.7 on 2026-04-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sales",
            "0016_rename_sales_docum_company_bbdced_idx_sales_docum_company_e03fd5_idx_and_more",
        ),
        ("sales", "0016_status_cleanup"),
    ]

    operations = []
