# Generated by Django 4.2.7 on 2026-04-18 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ["display_order", "price_try", "id"]},
        ),
        migrations.RenameField(
            model_name="plan",
            old_name="remove_branding",
            new_name="allow_ai_quote_extraction",
        ),
        migrations.RenameField(
            model_name="plan",
            old_name="price",
            new_name="price_try",
        ),
        migrations.RemoveField(
            model_name="subscriptionevent",
            name="plan",
        ),
        migrations.AddField(
            model_name="plan",
            name="allow_branding_removal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="allow_catalog_management",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="allow_email_sending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_emails_per_month",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_organizations",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_users",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="plan",
            name="price_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="billing_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="billing_currency",
            field=models.CharField(default="TRY", max_length=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="external_checkout_token",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="subscription",
            name="external_customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="subscriptionevent",
            name="plan_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="plan",
            name="billing_interval",
            field=models.CharField(
                choices=[("monthly", "Monthly")], default="monthly", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="external_provider",
            field=models.CharField(blank=True, default="iyzico", max_length=50),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="billing.plan",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("past_due", "Past Due"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("renewed", "Renewed"),
                    ("upgraded", "Upgraded"),
                    ("downgraded", "Downgraded"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("payment_succeeded", "Payment Succeeded"),
                    ("payment_failed", "Payment Failed"),
                    ("checkout_created", "Checkout Created"),
                ],
                max_length=50,
            ),
        ),
    ]
