# Generated by Django 4.2.7 on 2026-04-18 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_plan_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 5, 18, 0, 34, 9, 933714, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
