# Generated by Django 4.2.7 on 2026-04-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_subscription_current_period_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_contact_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="started_at",
            field=models.DateTimeField(),
        ),
    ]
