# Generated by Django 4.2.7 on 2026-04-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_plan_is_contact_only_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("company",),
                name="unique_active_subscription_per_company",
            ),
        ),
    ]
