# Generated by Django 4.2.7 on 2026-04-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_subscription_unique_active_subscription_per_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
