# Generated by Django 4.2.7 on 2023-12-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactcategory_contact_other_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contacts.contactcategory'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
