# Generated by Django 4.2.7 on 2024-02-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_categories_alter_contact_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('should_verify', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='contactcategory',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_category_name_per_user'),
        ),
        migrations.AddField(
            model_name='subscribelink',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contactcategory'),
        ),
    ]
