# Generated by Django 4.2.7 on 2024-02-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_subscribelink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribelink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
