# Generated by Django 4.2.7 on 2024-02-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_subscribelink_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_email_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_phone_number_per_user',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
